function define(
  arg0: string, 
  arg1: string[], 
  arg2: (
      rtc: any, 
      logging: any, 
      PCast: any, 
      RoomService: any, 
      AudioSpeakerDetector: any, 
      BandwidthMonitor: any, 
      UserMediaResolver: any, 
      PCastExpress: any, 
      RoomExpress: any, 
      ChannelExpress: any, 
      AdminApiProxyClient: any,
      _ :any , 
      assert:any, 
      event:any, 
      http:any, 
      disposable:any, 
      applicationActivityDetector:any, 
      DetectBrowser:any, 
      global:any, 
      DimensionsChangedMonitor:any, 
      streamEnums:any, 
      FeatureDetector:any,
      pcastLoggerFactory:any, 
      environment:any, 
      AudioContext:any, 
      PCastProtocol:any, 
      PCastEndPoint:any, 
      ScreenShareExtensionManager:any, 
      UserMediaProvider:any, 
      PeerConnectionMonitor:any, 
      DimensionsChangedMonitor:any, 
      metricsTransmitterFactory:any, 
      StreamTelemetry:any, 
      SessionTelemetry:any, 
      PeerConnection:any, 
      StreamWrapper:any, 
      PhenixLiveStream:any, 
      PhenixRealTimeStream:any, 
      FeatureDetector:any, 
      streamEnums:any, 
      BitRateMonitor:any, 
      phenixRTC:any, 
      sdpUtil:any
      ) => {  }) {
  throw new Error("Function not implemented.");
}